# Generated by Django 4.0.3 on 2022-05-22 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordmeaning',
            name='synonyms',
        ),
    ]
